### ISSUE TITLE
Field guide entries broken

### ISSUE THREAD

**Issue by chrissnyder** [zooniverse/wildcam-gorongosa#68]
Maybe a misplaced HTML tag somewhere?

Crocodile, tortoise

**Comment by aliburchard** [comment]
I think this actually has to do with the fact that crocodile and tortoise don't have species entries. When I saved the crocodile page as 'hartebeest.coffee', which _is_ a species in the list, it appears just fine.

**Comment by aliburchard** [comment]
Also - as a temporary fix, I think we can just say that we are launching the fieldguide _only_ with species from the species list, and remove these from the index.

**Comment by aliburchard** [comment]
Alright, @chrissnyder and @srallen could use your help here. 

There are two issues: 
1) species with no place on the species list do not appear (e.g. most of the reptiles).   I'm not worried about those - I'm happy to hide those from the main landing page for now.
2) species with 2-part names are funky. Wild dog, samango monkey, sable antelope, ground hornbill, and the lions are all broken. I _think_ this is because the button in the classifier creates a hyphenated url (wild-dog, for example), but the index.coffee script doesn't like hyphenated variable (which are used to actually build the field guide pages). I _think_ the solution is to change the hyphenated urls to underscored urls, but I don't know where in the codebase that happens.

**Comment by srallen** [comment]
I'll reassign this to myself for now and take a look when I work on some of the other bug fixes.

**Comment by srallen** [comment]
I fixed most of the issues except the featured image for honey badger isn't rendering in the browser for me, but it's not a 404. I think maybe something is wrong with the image itself? @ali, do you see this issue locally?

I'm going to guess Pygmy Chameleon needs to be hidden based on your first point.

I'm also getting a couple of 404s for hyneas and zebras featured images on demo, but it's fine locally.

**Comment by aliburchard** [comment]
There's something _super_ weird going on with this.

When you click on the "view field guide" button from the classifier, anything with a 2-word name is still broken, because it tries to go to a hyphenated url. 

However, the links from the field guide page do go to underscored urls, which do work fine for any species that has an entry in the classifier. I'm going to hide all of the reptiles for now, since they don't have entries in the classifier (and the pages won't display).

On top of that, there are some really weird cases where the feature images aren't displaying. Online, I don't see honey badger, hyena, or zebra. Hyena and zebra work for me locally, but honey badger doesn't. The filenames and code references seem to align just fine, so I'm not sure what's going on.

**Comment by aliburchard** [comment]
Figured (with Roger's help) some of the remaining issues. Going to close this and break this into sub-issues so I can split assignments.
